baseURL: "https://test.com"
languageCode: "en-gb"
title: "Test"
metaDataFormat: "yml"
version: "1.6.1"
theme: 
  - local
  - github.com/andrew-paterson/pandago

module:
  imports:
    - path: github.com/andrew-paterson/hugo-sundries
      disabled: false
      mounts:
        - source: partials
          target: layouts/partials/hugo-sundries
        - source: shortcodes
          target: layouts/shortcodes
        - source: scss
          target: assets/scss/hugo-sundries
        - source: js
          target: assets/js/hugo-sundries

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  body_classes: header-fixed
  image_dir: /media/images
  page_banners: 
    default_page_banner_for_large_screens: /media/images/page-banners/banner-pano.jpg
    default_page_banner_for_small_screens: /media/images/page-banners/banner-standard.jpg